db:
  hostname: localhost
  port: '3306'
  username: kittencoin
  password: kittencoin
  db: kittencoin
ssh:
  user: irsec
  filename: /home/irsec/password
users:
  team1: www.team1.com
  team2: www.team2.com
