db:
  hostname: localhost
  port: 3306
  username: kittencoin
  password: KittyPasswordy0
  db: KittenCoin
ssh:
  user: irsec
  filename: /home/irsec/password
users:
  team1: kcbox.team1.com
  team2: kcbox.team2.com
